services:
  - type: web
    name: meu-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi --log-file -"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: meu-banco
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
