# Generated by Django 5.2 on 2025-04-03 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_jogo_modo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='idade',
            new_name='ano',
        ),
    ]
