# Generated by Django 5.2 on 2025-04-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_usa_oculos_pessoa_oculos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='modo',
            field=models.CharField(choices=[('normal', 'Normal'), ('frase', 'Frase')], default='normal', max_length=10),
        ),
    ]
