# Generated by Django 5.2 on 2025-04-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('apelido', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.TextField()),
                ('jogo_favorito', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
