# Generated by Django 5.2 on 2025-04-06 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.IntegerField(default=0)),
                ('oculos', models.JSONField(default=list)),
                ('tatuagem', models.JSONField(default=list)),
                ('altura', models.IntegerField(default=0)),
                ('area_estudo', models.JSONField(default=list)),
                ('time', models.JSONField(default=list)),
                ('animal_de_estimacao', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogador', models.CharField(max_length=100)),
                ('tentativas', models.IntegerField(default=0)),
                ('concluido', models.BooleanField(default=False)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('modo', models.CharField(choices=[('normal', 'Normal'), ('frase', 'Frase')], default='normal', max_length=10)),
                ('alvo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_como_alvo', to='core.pessoa')),
            ],
        ),
    ]
