# Generated by Django 5.2 on 2025-04-02 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pessoa_delete_amigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='descricao',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='idade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='usa_oculos',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogador', models.CharField(max_length=100)),
                ('tentativas', models.IntegerField(default=0)),
                ('concluido', models.BooleanField(default=False)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('modo', models.CharField(choices=[('frase', 'Frase'), ('normal', 'Normal')], default='normal', max_length=10)),
                ('alvo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_como_alvo', to='core.pessoa')),
            ],
        ),
    ]
