# Generated by Django 5.2 on 2025-04-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_pessoa_descricao_pessoa_idade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='modo',
            field=models.CharField(choices=[('normal', 'Normal'), ('frase', 'Frase')], default='normal', max_length=10),
        ),
    ]
