# Generated by Django 5.2 on 2025-04-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_pessoa_altura_pessoa_area_estudo_pessoa_tatuagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='modo',
            field=models.CharField(choices=[('frase', 'Frase'), ('normal', 'Normal')], default='normal', max_length=10),
        ),
    ]
