# Generated by Django 5.2 on 2025-04-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_jogo_modo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='animal_de_estimacao',
            field=models.CharField(default='nenhum', max_length=100),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='modo',
            field=models.CharField(choices=[('frase', 'Frase'), ('normal', 'Normal')], default='normal', max_length=10),
        ),
    ]
