# Generated by Django 5.2 on 2025-04-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_pessoa_animal_de_estimacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='modo',
            field=models.CharField(choices=[('frase', 'Frase'), ('normal', 'Normal')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='area_estudo',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='time',
            field=models.JSONField(default=list),
        ),
    ]
